dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  firebase_core: ^2.24.2  # للمهام الأساسية
  firebase_messaging: ^14.7.10 # للإشعارات والرسائل
  google_mobile_ads: ^3.0.0 # للإعلانات والربح
